export const catalogoAseguradoras = [
  "GNP Seguros",
  "Quálitas Seguros",
  "AXA Seguros",
  "HDI Seguros",
  "Mapfre",
  "Chubb",
  "Zurich",
  "Seguros Banorte",
  "Seguros SURA",
  "AIG Seguros",
  "El Águila",
  "BBVA Seguros",
  "Seguros Banamex",
  "HSBC Seguros",
  "Inbursa",
  "Seguros BanRegio",
  "Seguros BanBajío",
  "Seguros BX+",
  "Scotia Seguros",
  "ANA Seguros",
  "Seguros Atlas",
  "Seguros Afirme",
  "General de Seguros",
  "El Potosí",
  "La Latino",
  "Primero Seguros",
  "Aseguradora Patrimonial",
  "Cardif",
  "Assurant",
  "RSA Seguros",
  "Tokio Marine",
  "Clupp",
  "Crabi",
  "Momento Seguros",
  "Wibe",
  "Allianz",
  "Allstate",
  "QBE",
  "MetLife",
  "Seguros Monterrey",
  "State Farm",
  "OTRA (NO ESPECIFICADA)"
];