export interface SolicitudCompra {
  id: number;
  folio: string;
  requiere_anticipo: number;
  motivo: string;
  fecha: string;
  c_c: number;
  centro_costo: string;
  usuario_destino: string;
  usuario_destino_id: number;
  intercompania: number;
  empresa: string;
  usuario_solicita: string;
  usuario_solicita_id: number;
  estatus: number;
  estado: string;
  claseEstado: string;
  auto_admin: number;
  auto_gg: number;
  auto_macro: number;
  tipo: number;
  orden_trabajo: string | null;
  id_orden_trabajo: number | null;
  folio_requisicion: string | null;
  formato_orden: string | null;
  tipo_mantenimiento: number;
  sistema: number;
  razon_cancelacion: string | null;
  multiUnidad: boolean;
  observaciones: string | null;
  total_orden: number;
  proveedor: string;
  folio_oc: string;
  modo_pago: string | null;
  pagado: boolean | null;
  motivo_revision: string | null;
  surtido: number;
  surtido_solicitado: boolean;
  facturas_xml: number;
  comprobantes_pago: number;
  complementos_pago: number;
  total_facturas: string;
  vencido: boolean;
}
